module Namabar
  module Endpoints
    # Create Verification Code
    # @param to [string] (required)
    # @param locale [String] (optional)
    # @param external_id [string] (optional)
    # @param code [string] (optional)
    # @param service_id [String] (required)
    # @param template_data [object] (optional)
    # @return [HTTParty::Response]
    def create_verification_code: (to: String, ?locale: String, ?external_id: String, ?code: String, service_id: String, ?template_data: Hash[String, untyped]) -> HTTParty::Response

    # Verify Verification Code
    # @param id [string] (required)
    # @param code [string] (required)
    # @return [HTTParty::Response]
    def verify_verification_code: (id: String, code: String) -> HTTParty::Response

    # Get Verification Code By Id
    # @param id [string] (required)
    # @return [HTTParty::Response]
    def get_verification_code_by_id: (id: String) -> HTTParty::Response

    # Send Message
    # @param type [String] (required)
    # @param to [string] (required)
    # @param external_id [string] (optional)
    # @param service_id [String] (required)
    # @param text [string] (optional)
    # @param template [String] (optional)
    # @return [HTTParty::Response]
    def send_message: (type: String, to: String, ?external_id: String, service_id: String, ?text: String, ?template: String) -> HTTParty::Response

    # Get Message
    # @param id [string] (required)
    # @return [HTTParty::Response]
    def get_message: (id: String) -> HTTParty::Response

    # Get Message Status
    # @param id [string] (required)
    # @return [HTTParty::Response]
    def get_message_status: (id: String) -> HTTParty::Response
  end
end
