module Namabar
  # The current version of the Namabar gem
  #
  # This constant follows semantic versioning (SemVer) conventions:
  # - MAJOR: Incompatible API changes
  # - MINOR: Backwards-compatible functionality additions
  # - PATCH: Backwards-compatible bug fixes
  #
  # @return [String] the current version string
  # @example Check the version
  #   puts Namabar::VERSION # => "0.1.0"
  #
  # @see https://semver.org/ Semantic Versioning specification
  VERSION: String
end 
